workflows:
  expo-android:
    name: Expo Android Build
    environment:
      node: latest
      npm: latest
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    scripts:
      - name: Install dependencies
        script: |
          npm install -g eas-cli
          npm install
      - name: Build APK
        script: |
          eas build --platform android --non-interactive --profile preview --group amiinhob
    artifacts:
      - build/**/*.apk
